# enable linux 14.04 environment
sudo: required
dist: xenial
language: python

python:
  - "3.5"
  - "3.7"

before_install:
  - bash .infrastructure/install_icu.sh

install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install pytz
  - pip install --editable .

script:
  - make test
